services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    expose:
      - "8100"
    environment:
      - DATABASE_URL=postgresql://traceability_user:TraceDB2024@92.120.147.79:5432/dummy_traceability
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "88:88"
    depends_on:
      - api
    restart: unless-stopped